import type { BKDocument } from '@/types/bk';

const esc = (value: unknown) => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const brl = (value = 0) => value.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const num = (value = 0) => value.toLocaleString('pt-BR', { maximumFractionDigits: 4 });
const day = (value?: string) => value ? new Date(value).toLocaleDateString('pt-BR') : '—';
const time = (value?: string) => value ? new Date(value).toLocaleTimeString('pt-BR') : '—';
const key = (value: string) => value.replace(/(.{4})/g, '$1 ').trim();
const field = (label: string, value: unknown, tone = '') => `<div class="cell ${tone}"><div class="label">${label}</div><div class="value">${esc(value || '—')}</div></div>`;

export function openDanfe(document: BKDocument, printImmediately = false) {
  const popup = window.open('', '_blank');
  if (!popup) throw new Error('O navegador bloqueou a janela do DANFE. Autorize pop-ups para este site.');
  const products = document.products.map((product) => {
    const fiscal = product.fiscal;
    return `<tr><td>${esc(product.code)}</td><td>${esc(product.description)}</td><td>${esc(product.ncm)}</td><td>${esc(fiscal?.icms.cst)}</td><td>${esc(product.cfop)}</td><td>${esc(product.unit)}</td><td class="right">${num(product.quantity)}</td><td class="right">${brl(product.unitValue)}</td><td class="right green">${brl(product.totalValue)}</td><td class="right">${brl(fiscal?.icms.baseCalc)}</td><td class="right red">${brl(fiscal?.icms.valor)}</td><td class="right">${brl(fiscal?.ipi.valor)}</td><td class="right">${num(fiscal?.icms.aliquota)}%</td><td class="right">${num(fiscal?.ipi.aliquota)}%</td></tr>`;
  }).join('');
  const installments = document.installments.length ? document.installments.map((item) => `${field('NÚMERO', item.number, 'yellow')}${field('DATA VCTO', day(item.dueDate), 'yellow')}${field('VALOR', brl(item.value), 'yellow')}`).join('') : `${field('NÚMERO', document.invoiceNumber)}${field('VALOR ORIGINAL', brl(document.originalValue))}${field('VALOR LÍQUIDO', brl(document.netInvoiceValue))}`;
  popup.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>DANFE ${esc(document.number)}</title><style>
  *{box-sizing:border-box}body{font-family:'Segoe UI',Arial,sans-serif;background:#f0f2f5;margin:0;padding:10px;color:#2c3e50}.actions{position:fixed;right:18px;top:18px;z-index:5;display:flex;gap:8px}.actions button{border:0;border-radius:7px;padding:9px 14px;background:#27ae60;color:#fff;font-weight:700;cursor:pointer}.danfe{width:794px;margin:auto;background:#fff;box-shadow:0 4px 20px #0002}.row{display:flex;border-bottom:1px solid #ddd}.cell{flex:1;padding:4px 6px;border-right:1px solid #ddd;min-width:0}.cell:last-child{border-right:0}.label{font-size:6px;font-weight:800;text-transform:uppercase;color:#64748b;margin-bottom:2px}.value{font-size:10px;font-weight:650;overflow-wrap:anywhere}.section{padding:3px 6px;font-size:7px;font-weight:900;text-transform:uppercase}.section.green{background:linear-gradient(90deg,#e8f5e9,#fff);color:#27ae60}.section.yellow{background:linear-gradient(90deg,#fff8e1,#fff);color:#f39c12}.section.red{background:linear-gradient(90deg,#fdf2f2,#fff);color:#e74c3c}.section.purple{background:linear-gradient(90deg,#f3e5f5,#fff);color:#9b59b6}.blue{background:#f0f8ff}.yellow{background:#fff8e1}.redbg{background:#fff5f5}.purplebg{background:#f3e5f5}.total{background:#e74c3c;color:#fff}.total .label{color:#fff}.green{color:#27ae60}.red{color:#e74c3c}.right{text-align:right}table{width:100%;border-collapse:collapse;font-size:8px}th{padding:3px;color:#64748b;border:1px solid #ddd;background:#f8f9fa;font-size:6px}td{padding:4px;border:1px solid #eee} @page{size:A4 portrait;margin:5mm}@media print{body{padding:0;background:#fff}.actions{display:none}.danfe{box-shadow:none;width:100%}}
  </style></head><body><div class="actions"><button onclick="window.print()">Imprimir / Salvar PDF</button></div><div class="danfe">
  <div class="row" style="border-bottom:2px solid #27ae60"><div style="flex:1;padding:7px"><div style="font-size:7px;font-weight:700;color:#64748b">RECEBEMOS DE ${esc(document.issuerName)} OS PRODUTOS/SERVIÇOS CONSTANTES NA NOTA FISCAL INDICADA AO LADO</div><div class="row" style="margin-top:5px;border:1px solid #27ae60">${field('DATA DE RECEBIMENTO',' ')}${field('IDENTIFICAÇÃO E ASSINATURA DO RECEBEDOR',' ')}</div></div><div style="width:165px;padding:7px;text-align:center;background:linear-gradient(135deg,#27ae60,#2ecc71);color:#fff"><b>NF-e</b><div>Nº <strong style="font-size:14px">${esc(document.number)}</strong></div><div>SÉRIE: <strong>${esc(document.series)}</strong></div></div></div>
  <div class="row" style="border-bottom:2px solid #27ae60"><div style="width:220px;padding:10px;text-align:center"><div style="font-size:20px;font-weight:900">SEZAM ZAAD</div><div style="font-size:9px">${esc(document.issuerName)}</div><div style="font-size:7px">${esc(document.issuerAddress)} — ${esc(document.issuerCity)}/${esc(document.issuerUf)}</div></div><div style="flex:1;padding:7px;text-align:center;background:#f8fff8"><b style="color:#27ae60">DANFE</b><div style="font-size:7px">DOCUMENTO AUXILIAR DA NOTA FISCAL ELETRÔNICA</div><div style="margin:5px"><span style="border:2px solid #27ae60;border-radius:3px;padding:2px 7px">${document.operationType === 'entrada' ? '0 - Entrada ✓' : '1 - Saída ✓'}</span></div><strong>Nº ${esc(document.number)}</strong><div style="font-size:8px">SÉRIE ${esc(document.series)} · FOLHA 1 de 1</div></div><div style="width:280px;padding:7px">${field('CHAVE DE ACESSO', key(document.accessKey), 'blue')}${field('PROTOCOLO DE AUTORIZAÇÃO', `${document.authorizationProtocol || '—'} — ${day(document.authorizationDate)} ${time(document.authorizationDate)}`, 'yellow')}</div></div>
  <div class="row">${field('NATUREZA DA OPERAÇÃO',document.operationNature)}${field('INSCRIÇÃO ESTADUAL',document.issuerIe,'blue')}${field('CNPJ',document.issuerTaxId,'redbg')}</div>
  <div class="section green">DESTINATÁRIO / REMETENTE</div><div class="row">${field('NOME/RAZÃO SOCIAL',document.recipientName)}${field('CNPJ/CPF',document.recipientTaxId,'redbg')}${field('DATA DA EMISSÃO',day(document.issueDate),'blue')}</div><div class="row">${field('ENDEREÇO',document.recipientAddress)}${field('MUNICÍPIO',document.recipientCity)}${field('UF',document.recipientUf,'blue')}${field('INSCRIÇÃO ESTADUAL',document.recipientIe)}${field('DATA/HORA SAÍDA',`${day(document.exitDate)} ${time(document.exitDate)}`,'yellow')}</div>
  <div class="section yellow">FATURA</div><div class="row">${installments}</div>
  <div class="section red">CÁLCULO DO IMPOSTO</div><div class="row">${field('BASE DE CÁLCULO ICMS',brl(document.icmsBase),'redbg')}${field('VALOR ICMS',brl(document.icmsValue),'redbg')}${field('VALOR PIS',brl(document.pisValue),'yellow')}${field('VALOR COFINS',brl(document.cofinsValue),'yellow')}${field('VALOR PRODUTOS',brl(document.productsValue),'blue')}</div><div class="row">${field('FRETE',brl(document.freightValue))}${field('SEGURO',brl(document.insuranceValue))}${field('DESCONTO',brl(document.discountValue))}${field('OUTRAS DESPESAS',brl(document.otherValue))}${field('VALOR IPI',brl(document.ipiValue))}${field('VALOR TOTAL DA NOTA',`R$ ${brl(document.invoiceValue)}`,'total')}</div>
  <div class="section purple">TRANSPORTADOR / VOLUMES TRANSPORTADOS</div><div class="row">${field('RAZÃO SOCIAL',document.carrierName,'purplebg')}${field('CNPJ/CPF',document.carrierTaxId)}${field('QUANTIDADE',num(document.volumeQuantity))}${field('PESO BRUTO',num(document.grossWeight))}${field('PESO LÍQUIDO',num(document.netWeight))}</div>
  <div class="section yellow">PRODUTOS / SERVIÇOS</div><table><thead><tr><th>CÓDIGO</th><th>DESCRIÇÃO</th><th>NCM/SH</th><th>CST</th><th>CFOP</th><th>UNID.</th><th>QTD</th><th>V. UNIT.</th><th>V. TOTAL</th><th>BC ICMS</th><th>V. ICMS</th><th>V. IPI</th><th>ALÍQ. ICMS</th><th>ALÍQ. IPI</th></tr></thead><tbody>${products || '<tr><td colspan="14">Sem itens cadastrados.</td></tr>'}</tbody></table>
  <div class="row" style="border-top:2px solid #27ae60"><div style="flex:2;padding:7px"><div class="section green">DADOS ADICIONAIS</div><div class="label">INFORMAÇÕES COMPLEMENTARES</div><div style="font-size:8px">${esc(document.additionalInfo)}</div></div><div style="width:220px;padding:7px;background:#f8fff8"><div class="section green">RESUMO</div><div class="value">Base ICMS: <b>${brl(document.icmsBase)}</b></div><div class="value">Valor ICMS: <b>${brl(document.icmsValue)}</b></div><div class="value">Produtos: <b>${brl(document.productsValue)}</b></div><div style="border-top:1px solid #ddd;margin-top:5px;padding-top:5px;font-size:12px;font-weight:900;color:#e74c3c">TOTAL: R$ ${brl(document.invoiceValue)}</div></div></div>
  </div><script>${printImmediately ? 'window.addEventListener("load",()=>setTimeout(()=>window.print(),150));' : ''}</script></body></html>`);
  popup.document.close();
}
